server: 
  port: 8201

spring: 
  application: 
    name: product #服务名称
  activemq: 
    broker-url: tcp://localhost:61616
    in-momory: true
    pool: 
      enabled: false
  redis: 
    hostName: 127.0.0.1
    port: 6379
    pool: 
      maxActive: 8
      maxWait: 1
      maxIdle: 8
      minIdle: 0
    timeout: 0
    
    #数据库连接配置
  datasource: 
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: liguoxing
    driver-class-name: com.mysql.jdbc.Driver
  #注册中心使用consul
#  cloud: 
#   consul: 
#     host: localhost
#     port: 8500
#     discovery: 
#       serviceName: user

#Mybatis配置
mybatis: 
  #Mapper.xml文件存放路径
  mapperLocations: classpath:**/mapper/*.xml
  #实体类路径
  type-aliases-package: com.product.pojo
  
#注册中心使用eureka
eureka: 
  instance: 
    prefer-ip-address: true
    instance-id: product-${server.port}
  client: 
    service-url: 
      defaultZone: http://localhost:8888/eureka

logging: 
  config: classpath:logback-spring.xml
  path: E:/log

debug: true

