server: 
  port: 8888
 
eureka: 
  instance: 
    hostname: localhost
  client: 
    register-with-eureka: false  #关闭自己作为服务注册
    fetch-registry: false
    healthcheck: 
      enabled: true
    service-url: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
 
#security:
  #basic:
    #enabled: true
  #user:
    #name: lgx #用户名和密码，等会访问的时候，会要求你登录，服务注册的时候也需要带着用户名和密码
    #password: liguoxing

debug: true