server: 
  port: 8666

#配置git仓库地址
spring: 
  cloud: 
    config: 
      server: 
        defaul-application-name: config-server
      git: 
        url: https://github.com/lgx520/springCloud
      #配置仓库路径
        search-paths: springCloud